# This file was generated by GoReleaser. DO NOT EDIT.
cask "otter" do
  version "0.1.6"

  on_macos do
    on_arm do
      sha256 "40451546cd6974ba4b477048f0328b73ecafbd7d0f2d6c2dee7746314a325cdf"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9b57e91e8d3d2fbbf5867843d9e90431a3d270a6d1cba8b20b884496190ec1a1"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "785cc68321b1a24e99531a8e26e936202c120bc0613db5427eb51c7572800c10"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "196bdd43e848e6c5cdc8b9865e4dfb072d4b807149896ee14a83e14a6cba53d9"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "otter"
  desc "Runtime for reliable Python integrations: scheduling, retries, state and logs"
  homepage "https://github.com/tkoizumi/otter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otter"
  binary "otterd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otter"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otterd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Two binaries are installed: `otter` (client and project runtime) and
    `otterd` (the same daemon, with its own flag defaults).

    Start a runtime for a project:

      cd my-project && otter start

    Python 3 is required by integrations that use the default external
    Python mode. An integration that opts into `python.mode: managed`
    prepares its own interpreter and needs no host Python.
  EOS
end
