# This file was generated by GoReleaser. DO NOT EDIT.
cask "otter" do
  version "0.1.9"

  on_macos do
    on_arm do
      sha256 "8c8771690462fce605e498c3fb5327cc864ebf6dea3aa3af014e65820ba53cd4"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3a5037683baef16f355ffd43470cab5297fabbf28fb7bdd5c779bd5614ae48ba"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "558f65fe13ee0ac8bdb37ebb422ec8d3cb934837b5a4114df193b4c9d11cb98d"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "778f5e9450cf7b3c1450e77491ea601a49ab97bca17346b828ee99810509794c"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "otter"
  desc "Runtime for reliable Python integrations: scheduling, retries, state and logs"
  homepage "https://github.com/tkoizumi/otter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otter"
  binary "otterd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otter"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otterd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Two binaries are installed: `otter` (client and project runtime) and
    `otterd` (the same daemon, with its own flag defaults).

    Start a runtime for a project:

      cd my-project && otter start

    Python 3 is required by integrations that use the default external
    Python mode. An integration that opts into `python.mode: managed`
    prepares its own interpreter and needs no host Python.
  EOS
end
