# This file was generated by GoReleaser. DO NOT EDIT.
cask "otter" do
  version "0.1.3"

  on_macos do
    on_arm do
      sha256 "96bce48eec19acdf1dcd18f7acadbce81b9888f0c3df8eb074f0a23fd49d7779"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c2c97949fd6b701694a7d40cd6c1996dc94969ddf38396e2cb8f691f053afeca"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e120dc36a2c0d0d03679e49415f134197f671944f14d0bba3eb7d909636438f1"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9dc9eb312dc47f15a2492124c2924042a4df0a0c5f35f38371b2e996e17000f6"
      url "https://github.com/tkoizumi/otter/releases/download/v#{version}/otter_#{version}_linux_amd64.tar.gz"
    end
  end

  name "otter"
  desc "Runtime for reliable Python integrations: scheduling, retries, state and logs"
  homepage "https://github.com/tkoizumi/otter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "otter"
  binary "otterd"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otter"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/otterd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Two binaries are installed: `otter` (client and project runtime) and
    `otterd` (the same daemon, with its own flag defaults).

    Start a runtime for a project:

      cd my-project && otter start

    Python 3 is required by integrations that use the default external
    Python mode. An integration that opts into `python.mode: managed`
    prepares its own interpreter and needs no host Python.
  EOS
end
